[project]
name = "ccxt_proxy"
version = "0.1.0"
requires-python = ">=3.11,<3.12"
dependencies = [
    "fastapi",
    "uvicorn",
    "ccxt",
    "aiofiles",
    "pydantic",
    "websockets",
    "pandas>=2.2.3",
]

[tool.uv]
dev-dependencies = []
